import './main_pane_style.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import React, { useState } from "react";

const Main_pane = ({setPageLoad}) =>{

    return  <div className="main-pane-container" onLoad={()=>setPageLoad('true')}>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam condimentum ligula in hendrerit laoreet. Integer urna arcu, convallis ut auctor viverra, finibus et orci. Vestibulum tincidunt ligula ut nulla euismod lacinia. Curabitur imperdiet massa nec semper euismod. Mauris ut arcu mattis, gravida arcu vel, porttitor quam. Curabitur porttitor id nulla sed sollicitudin. Suspendisse feugiat diam euismod fringilla mollis. Proin pharetra, libero nec dignissim scelerisque, elit risus laoreet velit, sit amet elementum risus nisi gravida erat. Aliquam dictum condimentum odio, vel varius sem facilisis vitae. Cras a nisl et ante mollis rhoncus vitae porttitor magna. Phasellus rhoncus vel velit id feugiat. Curabitur vitae sem hendrerit, vulputate lacus ut, ornare nunc. Vivamus pulvinar rutrum sapien, vel dictum libero posuere ac.

        Sed et interdum nunc. Integer varius in nibh et malesuada. Praesent rutrum sodales nunc et euismod. Nulla consectetur libero vel gravida finibus. Phasellus suscipit erat pharetra consequat gravida. Proin eget ipsum vulputate, suscipit leo at, tempus neque. Nunc quis velit vitae sem eleifend condimentum. Aenean feugiat eros lacinia vehicula pretium. Mauris at ipsum a est fermentum finibus. Donec quam ligula, cursus eget lacus id, scelerisque porta quam. Proin molestie diam enim, et finibus metus ullamcorper ac. Nullam facilisis porttitor nunc sit amet tempus. Aliquam erat volutpat.

        Proin gravida semper orci, eu auctor justo dignissim ac. Fusce sit amet erat ut purus interdum fermentum. Curabitur accumsan pharetra blandit. Quisque pulvinar erat et aliquam cursus. Sed blandit ullamcorper odio eu interdum. Integer blandit faucibus lacus at euismod. Proin sem dolor, semper et vulputate eu, lobortis nec enim. Nullam et cursus risus. Sed feugiat velit nulla. Praesent gravida faucibus accumsan. Duis id velit eu felis venenatis gravida varius non lacus. Ut congue vitae est sed hendrerit. Curabitur dictum ex non mi accumsan, eu porta risus pharetrLorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam condimentum ligula in hendrerit laoreet. Integer urna arcu, convallis ut auctor viverra, finibus et orci. Vestibulum tincidunt ligula ut nulla euismod lacinia. Curabitur imperdiet massa nec semper euismod. Mauris ut arcu mattis, gravida arcu vel, porttitor quam. Curabitur porttitor id nulla sed sollicitudin. Suspendisse feugiat diam euismod fringilla mollis. Proin pharetra, libero nec dignissim scelerisque, elit risus laoreet velit, sit amet elementum risus nisi gravida erat. Aliquam dictum condimentum odio, vel varius sem facilisis vitae. Cras a nisl et ante mollis rhoncus vitae porttitor magna. Phasellus rhoncus vel velit id feugiat. Curabitur vitae sem hendrerit, vulputate lacus ut, ornare nunc. Vivamus pulvinar rutrum sapien, vel dictum libero posuere ac.

        Sed et interdum nunc. Integer varius in nibh et malesuada. Praesent rutrum sodales nunc et euismod. Nulla consectetur libero vel gravida finibus. Phasellus suscipit erat pharetra consequat gravida. Proin eget ipsum vulputate, suscipit leo at, tempus neque. Nunc quis velit vitae sem eleifend condimentum. Aenean feugiat eros lacinia vehicula pretium. Mauris at ipsum a est fermentum finibus. Donec quam ligula, cursus eget lacus id, scelerisque porta quam. Proin molestie diam enim, et finibus metus ullamcorper ac. Nullam facilisis porttitor nunc sit amet tempus. Aliquam erat volutpat.

        Proin gravida semper orci, eu auctor justo dignissim ac. Fusce sit amet erat ut purus interdum fermentum. Curabitur accumsan pharetra blandit. Quisque pulvinar erat et aliquam cursus. Sed blandit ullamcorper odio eu interdum. Integer blandit faucibus lacus at euismod. Proin sem dolor, semper et vulputate eu, lobortis nec enim. Nullam et cursus risus. Sed feugiat velit nulla. Praesent gravida faucibus accumsan. Duis id velit eu felis venenatis gravida varius non lacus. Ut congue vitae est sed hendrerit. Curabitur dictum ex non mi accumsan, eu porta risus pharetra. Donec feugiat ex purus, eget dignissim est fringilla sed. Nullam sollicitudin urna sed lectus venenatis ultrices. Pellentesque ullamcorper in arcu eget laoreet.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam condimentum ligula in hendrerit laoreet. Integer urna arcu, convallis ut auctor viverra, finibus et orci. Vestibulum tincidunt ligula ut nulla euismod lacinia. Curabitur imperdiet massa nec semper euismod. Mauris ut arcu mattis, gravida arcu vel, porttitor quam. Curabitur porttitor id nulla sed sollicitudin. Suspendisse feugiat diam euismod fringilla mollis. Proin pharetra, libero nec dignissim scelerisque, elit risus laoreet velit, sit amet elementum risus nisi gravida erat. Aliquam dictum condimentum odio, vel varius sem facilisis vitae. Cras a nisl et ante mollis rhoncus vitae porttitor magna. Phasellus rhoncus vel velit id feugiat. Curabitur vitae sem hendrerit, vulputate lacus ut, ornare nunc. Vivamus pulvinar rutrum sapien, vel dictum libero posuere ac.

        Sed et interdum nunc. Integer varius in nibh et malesuada. Praesent rutrum sodales nunc et euismod. Nulla consectetur libero vel gravida finibus. Phasellus suscipit erat pharetra consequat gravida. Proin eget ipsum vulputate, suscipit leo at, tempus neque. Nunc quis velit vitae sem eleifend condimentum. Aenean feugiat eros lacinia vehicula pretium. Mauris at ipsum a est fermentum finibus. Donec quam ligula, cursus eget lacus id, scelerisque porta quam. Proin molestie diam enim, et finibus metus ullamcorper ac. Nullam facilisis porttitor nunc sit amet tempus. Aliquam erat volutpat.

        Proin gravida semper orci, eu auctor justo dignissim ac. Fusce sit amet erat ut purus interdum fermentum. Curabitur accumsan pharetra blandit. Quisque pulvinar erat et aliquam cursus. Sed blandit ullamcorper odio eu interdum. Integer blandit faucibus lacus at euismod. Proin sem dolor, semper et vulputate eu, lobortis nec enim. Nullam et cursus risus. Sed feugiat velit nulla. Praesent gravida faucibus accumsan. Duis id velit eu felis venenatis gravida varius non lacus. Ut congue vitae est sed hendrerit. Curabitur dictum ex non mi accumsan, eu porta risus pharetra. Donec feugiat ex purus, eget dignissim est fringilla sed. Nullam sollicitudin urna sed lectus venenatis ultrices. Pellentesque ullamcorper in arcu eget laoreet.a. Donec feugiat ex purus, eget dignissim est fringilla sed. Nullam sollicitudin urna sed lectus venenatis ultrices. Pellentesque ullamcorper in arcu eget laoreet.
        </p>
    </div>

}

export default Main_pane